services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rtlw
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - rtlw-network
    restart: always

  redis:
    image: redis:latest
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - rtlw-network
    restart: always

networks:
  rtlw-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local